### ISSUE TITLE
Images

### ISSUE THREAD

**Issue by Gann123** [nsfw-filter/nsfw-filter#157]
Most images are being blocked out by the filter
Many images that aren't anything close to NSFW such as pictures of cubes are being blocked out. In fact, most pictures, regardless of what they are, are being blocked out
Only NSFW pictures should be blocked out
Most pictures are being blocked out
Now I can't use chrome with the extension because I can't see pictures but I want the extension so it blocks out NSFW 
This is a Google Chrome on Windows 10

**Comment by YegorZaremba** [comment]
Hi @Gann123 thanks for your feedback
Yeah, we'll work on it in v1.5.0
Related: https://github.com/infinitered/nsfwjs/issues/324

**Comment by navendu-pottekkat** [comment]
@YegorZaremba We need to add one more category of images that are logos, banners and other such social media posts. They are not part of the training data. We will add those when we train our own model.

**Comment by wingman-jr-addon** [comment]
I can definitely say that adding that type of vector and vector-like content was quite important in getting my model to a place where I was more happy with it. I kept e.g. blocking avatars and Google doodles and the like; I still block them sometimes but the occurrence has greatly reduced due to feeding in images from my own browsing sessions. @navendu-pottekkat With the way NSFW.js classifies `drawings`, do you think that there would be confusing overlap between the two categories or are they quite distinct? I don't know how much vector art made it into `drawings`.

A related feature that popped up recently was setting up a whitelist for e.g. ReCaptcha https://github.com/wingman-jr-addon/wingman_jr/issues/84 so something like that may or may not be a good additional thing too?

**Comment by navendu-pottekkat** [comment]
Yeah, the nsfwjs model basically has the drawing class to distinguish hentai from normal cartoons. Since there are no other categories which has been trained on logos and other vector arts, this model would perform poorly against it. So we would need to retrain the model with those categories too or setup a feedback loop that would constantly improve the model.

The whitelist feature seems like a cool feature. @YegorZaremba What do you think?

**Comment by YegorZaremba** [comment]
Hi @navendu-pottekkat  @wingman-jr-addon great idea, critical logic
I have created ticket https://github.com/nsfw-filter/nsfw-filter/issues/166

Im so sorry guys, I'll be busy in next 1-1.5 months, so I cannot implement it

**Comment by navendu-pottekkat** [comment]
@YegorZaremba No problem, I have added help wanted label. Let's see if anyone picks it up.

**Comment by YegorZaremba** [comment]
@Gann123 We upload new version https://chrome.google.com/webstore/detail/nsfw-filter/kmgagnlkckiamnenbpigfaljmanlbbhh

This issue related to https://github.com/infinitered/nsfwjs/issues/324

Also you can play with strictness
![image](https://user-images.githubusercontent.com/31797554/167242455-de649fa5-ad72-44b9-b60f-510b9ada8f16.png)
