### ISSUE TITLE
Images sometimes not blocked on duckduckgo images on Firefox

### ISSUE THREAD

**Issue by user00124573** [nsfw-filter/nsfw-filter#170]
#### Bug description
See title

#### Expected result
Most or all the images should be blocked

#### Actual result
None of the images are blocked

#### Steps to reproduce
1. Open Firefox freshly. Ensure duckduckgo does not have cookies and is set to the default of moderate search.
2. Navigate to https://duckduckgo.com/?t=ffsb&q=porn&iax=images&ia=images (must enter url directly, cannot do a search and then switch to images or it will not happen)
3. It is on moderate search. Wait for all the images on that page to finish loading
4. Switch safesearch to off. None of the new images are blocked

#### Context
I encountered this issue randomly on duckduckgo. On my first try with the extension, images were blocked with safesearch to moderate or on, but I was confused why nothing was blocked with safesearch off. The issue seems semi-random, but the steps above have worked every time so far.

#### Your Environment
- Reproduced on Firefox 78.7.0esr on Debian
- Reproduced on Firefox 86.0 on Windows 7
- Was not able to reproduce on Chrome
- I have older machines so it might have something to do with performance or race conditions. If it doesn't work try testing on an older machine.

**Comment by YegorZaremba** [comment]
Hi @user00124573, it relates to #155 
I haven’t figured out how to fix it yet

**Comment by wingman-jr-addon** [comment]
@YegorZaremba As a quick and dirty test, you can just flip the bit in the tf.js minified file to see if it fixes it. Look for `failIfMajorPerformanceCaveat:!0`, this will be enough to force WebGL to keep working even if the browser doesn't think it's going to be optimal.
I had filed a bug with Mozilla as well as requested an optional feature in TF.js. Best place to start is probably on the [TF.js issue](https://github.com/tensorflow/tfjs/issues/4347) and follow the links through to the Bugzilla side. Mozilla actually decided to disable the flag check in Firefox because it has been causing more pain than help; I thought it was supposed to land in FF86 maybe?

**Comment by YegorZaremba** [comment]
Hi @user00124573 we stopped support Firefox, pls try our Chrome version https://chrome.google.com/webstore/detail/nsfw-filter/kmgagnlkckiamnenbpigfaljmanlbbhh/related
