### ISSUE TITLE
Which nsfwjs model does this extension use? What is the NSFW % Threshold? (If there is one)

### ISSUE THREAD

**Issue by lusseyarmet** [nsfw-filter/nsfw-filter#43]
Does anyone know which model (from https://github.com/infinitered/nsfwjs ) this extension uses? Because on https://nsfwjs.com/ there are three models, each with different results (the larger "huge" one being more accurate from what i can tell, even if it says it's the same % accuracy). 
And what's the threshold % for being NSFW? Is it different if it gets classified as "sexy", "porn" or any of the categories?
Overall, maybe adding a bit of detail about how it works to the description could be nice.
Thanks!

**Comment by YegorZaremba** [comment]
Hi @lusseyarmet thanks for contribution
please @navendu-pottekkat ask about model
We mark content as nsfw is top category includes `sexy, porn or hentai` you can see it [here ](https://github.com/navendu-pottekkat/nsfw-filter/blob/master/src/background.js#L62). But we plan to adjust percentages for it
`nsfw-filter` is under development right now, hope we will finish in next week

**Comment by navendu-pottekkat** [comment]
Hi @lusseyarmet ,

We use the **MobileNet V2** model that is available from [**here**](https://github.com/gantman/nsfw_model).

We are using the **MobileNet V2** version because it is ***lightweight*** and that is a core criterion for being able to run smoothly in the browser.

The original Inception model may be too laggy on some systems. If you have any suggestions on this model or a quantized version of this let us know and we will look into it.

For now, we look at the top prediction and if the category is NSFW(```Sexy, Porn or Hentai```) as @YegorZaremba mentioned, the content is filtered.

Could you suggest what we should add in the description? Or if you could make a PR that would be great!

**Comment by navendu-pottekkat** [comment]
@lusseyarmet Could you suggest what we should add in the description?

**Comment by YegorZaremba** [comment]
Closed. Inactive for 10 days
