### ISSUE TITLE
Update project tree and improve docs

### ISSUE THREAD

**Issue by navendu-pottekkat** [nsfw-filter/nsfw-filter#56]
The project tree is outdated and after v1.2.0 release is ready, update the tree.

**Comment by YegorZaremba** [comment]
I think `project tree` and`dependencies` are redundant info, I would like to get rid of them and make some [diagrams](https://www.google.com/search?q=UML+diagrams&newwindow=1&client=ubuntu&hs=bKv&channel=fs&sxsrf=ALeKk03o0Nrcobc9kky5ZQIBc-Xk8OvhxQ:1598275792564&source=lnms&tbm=isch&sa=X&ved=2ahUKEwjynfmm-bPrAhXGxIsKHSNPDc0Q_AUoAXoECA8QAw&biw=1848&bih=913) which describes how parts of `nsfw-filter` work together

Also I would like to update our demo gif with google chrome image searching because this website is more familiar for our users than scrolller.com/. Just present search results for `cats` and `sexy`

**Comment by navendu-pottekkat** [comment]
@YegorZaremba What kind of diagrams do you mean?

**Comment by YegorZaremba** [comment]
Closed because of lack classification
